schema_version: 1

context:
  name: pymzml
  version: "2.6.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pymzml-${{ version }}.tar.gz
  sha256: e36a352d5313e7d9b23882e5bcf6d8ce723e5ad6b0ae03d64dcbe62853bfcc57

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy >=1.8.0
    - regex

tests:
  - python:
      imports:
        - pymzml
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: high-throughput mzML parsing
  license: MIT
  license_file: LICENSE.txt
  homepage: http://pymzml.github.com

extra:
  recipe-maintainers:
    - hadim
